"""The committed build: Makefile, units.mk and per-version slices, symbols and link scripts.

A version's ROM is the concatenation, in ROM order, of
- one binary per published C unit (compile, `n64link place`, link alone at its address with symbols.ld),
- one binary per landed original-asm unit (hasm row: assemble src/<unit>.s, link alone at its address), and
- raw ROM slices for every byte range between them (copied from the original ROM with dd).
`make check` rebuilds every version and compares each ROM's sha1 with the original. The commands per unit come
from compilers.drivers, the same templates the runner fills, so make and unbake never disagree.
"""

from __future__ import annotations

import hashlib
import re
import shlex
from dataclasses import dataclass
from pathlib import Path

from unbake import atomic as atomic_files
from unbake import cache, inputs
from unbake import cache as retention
from unbake.compilers import drivers
from unbake.compilers import registry as compiler_registry
from unbake.config import Held, Host, Project
from unbake.layout import split
from unbake.process import named as cause_named

# Bump when this step's output changes for the same inputs. Keys never digest the tool's code.
SCHEMA = 14

# CI pins: full commit SHAs and an image digest (tool data, never config).
CHECKOUT = ("actions/checkout", "11d5960a326750d5838078e36cf38b85af677262", "v4.4.0")
UPLOAD_ARTIFACT = ("actions/upload-artifact", "ea165f8d65b6e75b540449e92b4886f43607fa02", "v4.6.2")
PYTHON_IMAGE = "python:3.11-slim@sha256:0dd364ba7e10242f07755449e3a3d0e35f9efd987952737b90def6709ab0c5ce"
HEADER = "# Generated by unbake. Do not edit; unbake regenerates it from config.toml and versions/.\n"
MAKE_VALUES: dict[str, tuple[str, ...]] = {
    "cc": ("$(abspath $(CC))",),
    "cpp": ("$(CPP)",),
    "as": ("$(AS)",),
    "n64link": ("$(N64LINK)",),
    "includes": ("$(INCLUDES) $(COMPILER_INCLUDES) $(UNIT_INCLUDES)",),
    "codegen": ("$(CODEGEN) $(UNIT_CODEGEN)",),
    "preprocess": ("$(PREPROCESS_FLAGS)",),
    "defines": ("$(COMPILER_DEFINES) $(VERSION_DEFINES) $(CONSUMER) $(UNIT_DEFINES)",),
    "cppflags": ("$(CPPFLAGS)",),
    "asflags": ("$(ASSEMBLER_FLAGS)",),
    "source": ("src/$(*F).c",),
    "name": ("$(*F)",),
}


@dataclass(frozen=True)
class Unit:
    """One native producer in one version: C code, original assembly, or initialized DATA."""

    name: str
    address: int
    start: int
    size: int
    kind: str = "c"


@dataclass(frozen=True)
class Resource(Unit):
    """Symbolic assembler source stored in ROM separately from its execution address."""

    source: str = ""
    execution_address: int = 0
    section: str = ""
    asflags: tuple[str, ...] = ()
    assembler: str = "gnu"
    output: str = ""
    cppflags: tuple[str, ...] = ()


@dataclass(frozen=True)
class MixedData(Unit):
    """An explicit compiler table subextent of an existing published C producer."""

    section: str = ""
    offset: int = 0
    pointer_bias: int = 0
    code_address: int = 0
    code_start: int = 0
    code_size: int = 0


def relative(project: Project, path: Path) -> str:
    return str(path.relative_to(project.root)) if path.is_relative_to(project.root) else str(path)


def words(values: tuple[str, ...] | list[str]) -> str:
    for value in values:
        if any(c in value for c in " \t\n'\"$#\\"):
            raise Held(
                cause_named(
                    "buildfiles.flag",
                    f"buildfiles.flag: {value!r}: flags may not contain spaces, quotes, $, # or \\",
                    owner="buildfiles",
                    stage="buildfiles",
                )
            )
    return " ".join(values)


SOURCE_SUFFIX = {"c": ".c", "hasm": ".s"}


def units(project: Project, version: str) -> list[Unit]:
    """Published C and original-asm rows of VERSION in ROM order; each must have src/<unit>.c or src/<unit>.s."""
    result = []
    for row in split.functions(project, version):
        if row.kind not in SOURCE_SUFFIX:
            continue
        name = Path(row.path).name
        suffix = SOURCE_SUFFIX[row.kind]
        if not (project.src / f"{name}{suffix}").is_file():
            raise Held(
                cause_named(
                    "buildfiles.source",
                    f"buildfiles.source: {version} row {name} has no src/{name}{suffix}",
                    owner="buildfiles",
                    stage="buildfiles",
                )
            )
        result.append(Unit(name, row.address, row.start, row.end - row.start, row.kind))
    result.extend(data_units(project, version))
    result.extend(resource_bindings(project, version))
    if len({(unit.kind, unit.name) for unit in result}) != len(result):
        raise Held(
            cause_named(
                "buildfiles.source",
                "ambiguous duplicate source unit",
                owner="buildfiles",
                stage="buildfiles",
            )
        )
    return sorted(result, key=lambda unit: unit.start)


def data_bindings(project: Project, version: str, *, text: str | None = None) -> dict[Unit, tuple[str, str]]:
    """Explicit C source paths in existing DATA rows, independently of function inventory."""
    path = project.version(version).split
    _, _, segments = split.layout(path) if text is None else split.parse_layout(path, text)
    result = {}
    names: set[str] = set()
    for segment in segments:
        for row in segment.rows:
            declared = Path(row.path)
            if row.kind.lstrip(".") not in {"data", "rodata", "rdata", "sdata"} or declared.suffix != ".c":
                continue
            source = project.root / declared
            if source.parent != project.src or source.is_symlink():
                raise Held(
                    cause_named(
                        "buildfiles.source",
                        f"{version}: declared DATA source missing or outside src: {row.path}",
                        owner="buildfiles",
                        stage="buildfiles",
                    )
                )
            stop = split.end(row)
            if stop <= row.start:
                raise Held(
                    cause_named(
                        "buildfiles.data",
                        "initialized DATA row has invalid bounds",
                        owner="buildfiles",
                        stage="buildfiles",
                    )
                )
            unit = Unit(source.stem, split.address(row, path), row.start, stop - row.start, "data")
            fields = segment.fields
            if any(key.startswith("data_") for key in fields):
                if {key for key in fields if key.startswith("data_")} != {
                    "data_section",
                    "data_offset",
                    "data_pointer_bias",
                }:
                    raise Held(
                        cause_named(
                            "buildfiles.data",
                            "complete explicit mixed DATA fields required",
                            owner="buildfiles",
                            stage="buildfiles",
                        )
                    )
                section = fields.get("data_section", "")
                if section not in {".rdata", ".rodata"}:
                    raise Held(
                        cause_named(
                            "buildfiles.data",
                            "data_section must name a compiler constant section",
                            owner="buildfiles",
                            stage="buildfiles",
                        )
                    )
                offset = split.number(fields.get("data_offset"), "data_offset")
                bias = split.number(fields.get("data_pointer_bias"), "data_pointer_bias")
                code = [
                    candidate
                    for part in segments
                    for candidate in part.rows
                    if candidate.kind == "c" and Path(candidate.path).name == source.stem
                ]
                if len(code) != 1 or bias not in {0, 0x80000000} or offset % 4 or unit.size % 4 or unit.address % 4:
                    raise Held(
                        cause_named(
                            "buildfiles.data",
                            "mixed DATA needs one published C row and aligned table bounds",
                            owner="buildfiles",
                            stage="buildfiles",
                        )
                    )
                code_address = split.address(code[0], path)
                code_size = split.end(code[0]) - code[0].start
                if (
                    unit.address < offset
                    or unit.address + unit.size > 2**32
                    or code_size <= 0
                    or code_address % 4
                    or code_address + code_size > 2**32
                ):
                    raise Held(
                        cause_named(
                            "buildfiles.data",
                            "mixed DATA placement exceeds target bounds",
                            owner="buildfiles",
                            stage="buildfiles",
                        )
                    )
                unit = MixedData(
                    unit.name,
                    unit.address,
                    unit.start,
                    unit.size,
                    "data",
                    section,
                    offset,
                    bias,
                    code_address,
                    code[0].start,
                    code_size,
                )
            if unit.name in names:
                raise Held(
                    cause_named(
                        "buildfiles.source",
                        "duplicate DATA source binding",
                        owner="buildfiles",
                        stage="buildfiles",
                    )
                )
            names.add(unit.name)
            result[unit] = (row.path, row.kind)
    return result


def data_units(project: Project, version: str) -> list[Unit]:
    """Declared initialized DATA sources must exist; never replace them with raw ROM."""
    result = data_bindings(project, version)
    for unit in result:
        if not (project.src / (unit.name + ".c")).is_file():
            raise Held(
                cause_named(
                    "buildfiles.source",
                    f"{version}: declared DATA source missing: src/{unit.name}.c",
                    owner="buildfiles",
                    stage="buildfiles",
                )
            )
    return sorted(result, key=lambda unit: unit.start)


def data_link_script(project: Project, version: str) -> str:
    return (
        "OUTPUT_ARCH(mips)\nSECTIONS\n{\n"
        "  .data : SUBALIGN(1) { *(.rdata .rdata.* .rodata .rodata.* .data .data.* .sdata .sdata.* .lit4 .lit8) }\n"
        "  /DISCARD/ : { *(*) }\n}\n"
        f"INCLUDE versions/{version}/symbols.ld\n"
    )


def mixed_data_link_script(project: Project, version: str, unit: MixedData) -> str:
    """Keep the real code VMA while the native linker resolves local table relocations."""
    return (
        "OUTPUT_ARCH(mips)\nSECTIONS\n{\n"
        f"  .text 0x{unit.code_address:X} : {{ *(.text) }}\n"
        f"  .data 0x{unit.address - unit.offset:X} : SUBALIGN(1) {{ *({unit.section}) }}\n"
        "  /DISCARD/ : { *(*) }\n}\n"
        f"INCLUDE versions/{version}/symbols.ld\n"
    )


def resource_bindings(project: Project, version: str, *, text: str | None = None) -> dict[Resource, str]:
    """Explicit resource rows; the segment vram is resident storage, execution_vram is separate."""
    path = project.version(version).split
    _, _, segments = split.layout(path) if text is None else split.parse_layout(path, text)
    result: dict[Resource, str] = {}
    for segment in segments:
        for row in segment.rows:
            if row.kind != "resource":
                continue
            source = project.root / row.path
            resources = project.root / "resources"
            if (
                Path(row.path).is_absolute()
                or not source.resolve().is_relative_to(resources.resolve())
                or source.suffix != ".s"
                or source.is_symlink()
                or (text is None and not source.is_file())
            ):
                raise Held(
                    cause_named(
                        "buildfiles.resource",
                        f"{version}: resource source must exist under resources/: {row.path}",
                        owner="buildfiles",
                        stage="buildfiles",
                    )
                )
            name = "_".join(source.relative_to(resources).with_suffix("").parts)
            fields = segment.fields
            assembler = fields.get("resource_assembler", "gnu")
            output = fields.get("resource_output", "")
            if assembler not in {"gnu", "armips"} or (assembler == "armips" and output not in {"code", "data"}):
                raise Held(
                    cause_named(
                        "buildfiles.resource",
                        "unsupported resource assembler/output",
                        owner="buildfiles",
                        stage="buildfiles",
                    )
                )
            if assembler == "armips":
                name += "_" + output
            elif output:
                raise Held(
                    cause_named(
                        "buildfiles.resource",
                        "GNU resource uses a native section",
                        owner="buildfiles",
                        stage="buildfiles",
                    )
                )
            split.name(name, "resource name")
            execution = split.number(fields.get("execution_vram"), "resource execution_vram")
            section = fields.get("resource_section", "")
            if assembler == "gnu" and not re.fullmatch(r"\.[A-Za-z_][A-Za-z_0-9.]*", section):
                raise Held(
                    cause_named(
                        "buildfiles.resource",
                        "resource_section must name one native section",
                        owner="buildfiles",
                        stage="buildfiles",
                    )
                )
            try:
                flags = tuple(shlex.split(fields.get("resource_asflags", "")))
                cppflags = tuple(shlex.split(fields.get("resource_cppflags", "")))
            except ValueError as error:
                raise Held(
                    cause_named("buildfiles.resource", str(error), owner="buildfiles", stage="buildfiles")
                ) from error
            if assembler == "gnu":
                words(flags)
            else:
                resource_args(flags)
            words(cppflags)
            size = split.end(row) - row.start
            address = split.address(row, path)
            if size <= 0 or execution + size > 2**32 or address + size > 2**32:
                raise Held(
                    cause_named(
                        "buildfiles.resource",
                        "resource placement exceeds target bounds",
                        owner="buildfiles",
                        stage="buildfiles",
                    )
                )
            if any(resource.name == name for resource in result):
                raise Held(
                    cause_named(
                        "buildfiles.resource", "duplicate resource output name", owner="buildfiles", stage="buildfiles"
                    )
                )
            resource = Resource(
                name,
                address,
                row.start,
                size,
                "resource",
                row.path,
                execution,
                section,
                flags,
                assembler,
                output,
                cppflags,
            )
            result[resource] = row.path
    for code, data in resource_pairs(tuple(result)):
        if (code.asflags, code.cppflags) != (data.asflags, data.cppflags):
            raise Held(
                cause_named(
                    "buildfiles.resource", "paired resource options differ", owner="buildfiles", stage="buildfiles"
                )
            )
    return result


def resource_args(args: tuple[str, ...]) -> str:
    """Quote assembler arguments without admitting Make expansions or line/comment syntax."""
    if any(any(character in argument for character in "$#\n\r") for argument in args):
        raise Held(
            cause_named("buildfiles.resource", "unsafe resource argument", owner="buildfiles", stage="buildfiles")
        )
    return " ".join(shlex.quote(argument) for argument in args)


def resource_pairs(resources: tuple[Resource, ...]) -> list[tuple[Resource, Resource]]:
    grouped: dict[str, dict[str, Resource]] = {}
    for resource in resources:
        if resource.assembler == "armips":
            grouped.setdefault(resource.source, {})[resource.output] = resource
    result = []
    for outputs in grouped.values():
        if set(outputs) != {"code", "data"}:
            raise Held(
                cause_named(
                    "buildfiles.resource",
                    "armips source needs code and data rows",
                    owner="buildfiles",
                    stage="buildfiles",
                )
            )
        result.append((outputs["code"], outputs["data"]))
    return result


def resource_inputs(project: Project) -> tuple[Path, ...]:
    """The retained assembler include/header inputs also determine resource freshness."""
    return tuple(
        sorted(p for p in (project.root / "resources").rglob("*") if p.suffix in {".h", ".inc"} and p.is_file())
    )


def resource_link_script(project: Project, version: str, resource: Resource) -> str:
    return (
        "OUTPUT_ARCH(mips)\nSECTIONS\n{\n"
        f"  .resource 0x{resource.execution_address:X} : AT(0x{resource.address:X}) "
        f"{{ KEEP(*({resource.section})) }}\n"
        "  /DISCARD/ : { *(*) }\n}\n"
        f'ASSERT(SIZEOF(.resource) == {resource.size}, "resource size differs from ROM extent")\n'
        f"INCLUDE versions/{version}/symbols.ld\n"
    )


def windows(project: Project, version: str) -> list[tuple[int, int, int]]:
    """(vram, rom, size) for every mapped segment and resident copy; place proves constants inside them."""
    _, _, segments = split.layout(project.version(version).split)
    result = []
    for segment in segments:
        fields = segment.fields
        if "vram" not in fields or "start" not in fields or segment.end is None:
            continue
        start = split.number(fields["start"], "segment start")
        result.append((split.number(fields["vram"], "segment vram"), start, segment.end - start))
    for mapping in project.resident_mappings.get(version, ()):
        result.append((mapping.address, mapping.start, mapping.end - mapping.start))
    return result


_LINKER_ALIAS = re.compile(r"^//\s*unbake linker alias:\s*([A-Za-z_]\w*)\s*=\s*0x([0-9A-Fa-f]+);", re.M)
_ADDRESS_NAMED = re.compile(r"\b(?:D|func)_([0-9A-F]{8})\b")


def named_address(name: str) -> int | None:
    """The vram an address-named symbol (D_XXXXXXXX, func_XXXXXXXX) encodes; None for any other name."""
    match = _ADDRESS_NAMED.fullmatch(name)
    return int(match[1], 16) if match else None


def address_named(project: Project) -> dict[str, int]:
    """Names splat derives from a vram (D_XXXXXXXX, func_XXXXXXXX) that published C or headers spell."""
    names: dict[str, int] = {}
    for path in (*project.src.glob("*.c"), *(p for root in project.include for p in root.rglob("*.h"))):
        for match in _ADDRESS_NAMED.finditer(path.read_text(errors="replace")):
            names[match[0]] = int(match[1], 16)
    return names


def symbols_ld(project: Project, version: str) -> str:
    """Every known symbol as PROVIDE, so a unit linked alone resolves its external references.

    Data that stays a raw ROM slice has no label in any object. An address-named symbol the sources spell
    and the version's symbol file lacks is provided at the address its name encodes (version branches name
    their own addresses); a wrong address cannot pass, because make check compares the whole ROM.
    """
    path = project.version(version).symbols
    _, rows = split.symbols(path)
    provided = {name: address for name, (address, _, _) in rows.items()}
    # A shared name whose address already has another splat symbol in this version is kept as a comment.
    for name, address in _LINKER_ALIAS.findall(path.read_text()):
        provided.setdefault(name, int(address, 16))
    for name, address in address_named(project).items():
        provided.setdefault(name, address)
    from unbake.compilers.runtime import bindings

    for name, address in bindings(project, version).items():
        if name in provided and provided[name] != address:
            raise Held(
                cause_named(
                    "symbols.runtime_identity",
                    f"symbols.runtime_identity: {name}: configured address disagrees with proved native code",
                    owner="buildfiles",
                    stage="buildfiles",
                )
            )
        provided[name] = address
    return "".join(f"PROVIDE({name} = 0x{address:08X});\n" for name, address in sorted(provided.items()))


def link_script(project: Project, version: str) -> str:
    return (
        "OUTPUT_ARCH(mips)\n"
        "SECTIONS\n{\n  .text : { *(.text) }\n  /DISCARD/ : { *(*) }\n}\n"
        f"INCLUDE versions/{version}/symbols.ld\n"
    )


def slices_mk(project: Project, version: str) -> str:
    """Units, raw slices between them, constant windows and the piece order of the ROM.

    Every name carries the version prefix (`<v>.U.<unit>`), so the Makefile includes every version at once.
    Slice offsets and sizes are decimal: GNU dd reads skip= and count= as decimal (0x is a multiplier)."""
    rom_size = project.version(version).baserom.stat().st_size
    build = f"build/{version}"
    lines = [HEADER]
    lines.append(f"{version}.BASEROM := {relative(project, project.version(version).baserom)}\n")
    lines.append(f"{version}.DEFINES := {words(['-D' + macro for macro in project.version(version).macros])}\n")
    windows_ = " ".join(f"0x{v:X}:0x{r:X}:0x{s:X}" for v, r, s in windows(project, version))
    lines.append(f"{version}.MAP := {windows_}\n")
    pieces = []
    cursor = 0
    for unit in units(project, version):
        if unit.start < cursor:
            raise Held(
                cause_named(
                    "buildfiles.overlap",
                    f"buildfiles.overlap: {version} {unit.name} starts inside the previous row",
                    owner="buildfiles",
                    stage="buildfiles",
                )
            )
        if unit.start > cursor:
            lines.append(f"{version}.S.{cursor:08X} := {cursor} {unit.start - cursor}\n")
            pieces.append(f"{build}/slices/{cursor:08X}.bin")
        namespace = {"data": "D", "resource": "R"}.get(unit.kind, "U")
        lines.append(f"{version}.{namespace}.{unit.name} := 0x{unit.address:X}:0x{unit.start:X}:0x{unit.size:X}\n")
        directory = {"c": "units", "hasm": "hasm", "data": "data", "resource": "resources"}[unit.kind]
        pieces.append(f"{build}/{directory}/{unit.name}.bin")
        if isinstance(unit, MixedData):
            lines.append(f"{version}.D.{unit.name}.SECTION := {unit.section}\n")
            lines.append(f"{version}.D.{unit.name}.OFFSET := {unit.offset}\n")
            lines.append(f"{version}.D.{unit.name}.BIAS := 0x{unit.pointer_bias:X}\n")
            lines.append(
                f"{build}/data/{unit.name}.bin: {build}/units/{unit.name}.bin tools/report-verifier.zip "
                f"versions/{version}/data/{unit.name}.ld\n"
            )
        if isinstance(unit, Resource) and unit.assembler == "gnu":
            lines.append(f"{version}.R.{unit.name}.ASFLAGS := {words(unit.asflags)}\n")
            lines.append(
                f"{build}/resources/{unit.name}.bin: {unit.source} Makefile versions/{version}/slices.mk "
                f"versions/{version}/resources/{unit.name}.ld versions/{version}/symbols.ld | {build}/resources\n"
                "\t$(Q)$(RESOURCE_BIN)\n"
            )
        cursor = unit.start + unit.size
    if cursor > rom_size:
        raise Held(
            cause_named(
                "buildfiles.rom_size",
                f"buildfiles.rom_size: {version} rows end past the ROM",
                owner="buildfiles",
                stage="buildfiles",
            )
        )
    if cursor < rom_size:
        lines.append(f"{version}.S.{cursor:08X} := {cursor} {rom_size - cursor}\n")
        pieces.append(f"{build}/slices/{cursor:08X}.bin")
    lines.append(f"{version}.PIECES := \\\n" + " \\\n".join(f"  {piece}" for piece in pieces) + "\n")
    dependencies = words([relative(project, p) for p in resource_inputs(project)])
    for code, data in resource_pairs(tuple(resource_bindings(project, version))):
        code_target = f"{build}/resources/{code.name}.bin"
        data_target = f"{build}/resources/{data.name}.bin"
        base = code.name.removesuffix("_code")
        expanded = f"{build}/resources/{base}.S"
        preprocessor = f"$(CPP) {words(code.cppflags)} {code.source} > {expanded} && " if code.cppflags else ""
        lines.append(
            f"{code_target} {data_target} &: {code.source} {dependencies} Makefile versions/{version}/slices.mk "
            f"| {build}/resources\n"
            f"\t$(Q){preprocessor}$(ARMIPS) {expanded if code.cppflags else code.source} "
            f"-strequ CODE_FILE {code_target}.tmp -strequ DATA_FILE {data_target}.tmp {resource_args(code.asflags)} && "
            f'[ "$$(wc -c < {code_target}.tmp)" -eq {code.size} ] && '
            f'[ "$$(wc -c < {data_target}.tmp)" -eq {data.size} ] && '
            f"mv {code_target}.tmp {code_target} && mv {data_target}.tmp {data_target}\n"
        )
    return "".join(lines)


def units_mk(project: Project, *, names: tuple[str, ...] | None = None) -> str:
    """Pattern-specific values (all versions) for units off the default compiler or with their own flags."""
    lines = [HEADER]
    default = project.compilers[project.default_compiler]
    from unbake.work import attempts

    selected = sorted({path.stem for path in project.src.glob("*.c")}) if names is None else names
    for name in selected:
        targets = f"build/%/src/{name}.i build/%/src/{name}.key build/%/units/{name}.bin build/%/data/{name}.bin"
        compiler = project.compiler_for(name)
        effective = [
            *(f"-I{relative(project, path)}" for path in project.include),
            *compiler.cflags,
            "-DUNBAKE_VERSION_PLACEHOLDER",
            *project.unit_flags.get(name, ()),
        ]
        prep, _ = drivers.stage_flags(compiler.id, effective)
        rendered = words(list(prep)).replace("-DUNBAKE_VERSION_PLACEHOLDER", "$(VERSION_DEFINES) $(CONSUMER)")
        if attempts.guard_present((project.src / (name + ".c")).read_text()):
            rendered += " -DNON_MATCHING"
        lines.append(f"{targets}: PREPROCESS_FLAGS = {rendered}\n")
        if compiler.id != default.id:
            c_includes, c_codegen, c_defines = drivers.compiler_parts(project, compiler.id)
            lines.append(f"{targets}: KIND := {compiler.kind}\n")
            lines.append(f"{targets}: CC := {relative(project, compiler.cc)}\n")
            lines.append(f"{targets}: CODEGEN := {words(c_codegen)}\n")
            lines.append(f"{targets}: COMPILER_INCLUDES := {words(c_includes)}\n")
            lines.append(f"{targets}: COMPILER_DEFINES := {words(c_defines)}\n")
            lines.append(f"{targets}: ASSEMBLER_FLAGS := {words(list(drivers.assembly_flags(project, compiler.id)))}\n")
            lines.append(f"{targets}: TRIM := {'' if drivers.preserves_padding(compiler.kind) else '--trim'}\n")
        u_includes, u_codegen, u_defines = drivers.unit_parts(project, name)
        if u_includes:
            lines.append(f"{targets}: UNIT_INCLUDES := {words(u_includes)}\n")
        if u_codegen:
            lines.append(f"{targets}: UNIT_CODEGEN := {words(u_codegen)}\n")
        if u_defines:
            lines.append(f"{targets}: UNIT_DEFINES := {words(u_defines)}\n")
        guard = drivers.consumer_define(project, name)
        if guard is not None:
            lines.append(f"{targets}: CONSUMER := {guard}\n")
    return "".join(lines)


def _recipe(template: tuple[str, ...]) -> str:
    return " ".join(drivers.render(template, MAKE_VALUES))


def _kind_recipes(kind: str) -> str:
    """PREPROCESS_<kind> writes UNIT.i and UNIT.d; COMPILE_<kind> turns UNIT.i into UNIT.o inside the unit's directory.

    A cpp preprocess writes the dependency file in the same pass; a compiler driver's -E needs its own cpp -MM."""
    template = drivers.templates(kind)
    preprocess = template["preprocess"]
    compile_ = template["compile"]
    assert preprocess is not None and compile_ is not None
    from unbake.compilers.families import family_for_kind

    prep = family_for_kind(kind).make_preprocess(_recipe)
    commands = [_recipe(compile_)]
    if template["assemble"] is not None:
        commands.append(_recipe(template["assemble"]))
    return f"PREPROCESS_{kind} = {prep}\nCOMPILE_{kind} = {' && '.join(commands)}\n"


def native_compile_recipe(project: Project, name: str, tools: drivers.Tools) -> str:
    """The existing Make CAS command, retaining its significant empty-variable spaces.

    Tools must name the actual producing Make arguments; never guess alternative
    spellings to make a historical key pass. Make's key strips only CURDIR.
    """
    compiler = project.compiler_for(name)
    _, codegen, _ = drivers.compiler_parts(project, compiler.id)
    _, unit_codegen, _ = drivers.unit_parts(project, name)
    recipe = _kind_recipes(compiler.kind).split("COMPILE_" + compiler.kind + " = ", 1)[1].rstrip("\n")
    for variable, value in {
        "$(abspath $(CC))": relative(project, compiler.cc),
        "$(CODEGEN)": words(codegen),
        "$(UNIT_CODEGEN)": words(unit_codegen),
        "$(N64LINK)": tools.n64link,
        "$(AS)": tools.mips_as,
        "$(ASSEMBLER_FLAGS)": words(list(drivers.assembly_flags(project, compiler.id))),
        "$(*F)": name,
    }.items():
        recipe = recipe.replace(variable, value)
    return recipe.replace(str(project.root) + "/", "")


# The expanded unit tracks source/header/command freshness; the key changes only with object content.
# One shell preprocesses and compiles missing objects; an unchanged key never forces a binary relink.
# The key is sha1(toolchain pins + root-relative compile commands), then sha1(UNIT.i). Publication is atomic,
# and two versions racing on one key write identical bytes. Place and link read the shared object and never write it.
UNIT_RECIPES = r"""VER = $(word 2,$(subst /, ,$@))
VERSION_DEFINES = $($(VER).DEFINES)
TOOLCHAIN := $(firstword $(shell cat tools/compilers.sha256 tools/n64link.version | sha1sum))
UNIT_KEY = printf '%s\n' '$(VER) $(*F)'; \
  $(PREPROCESS_$(KIND)) && \
  set -- $$(printf '%s\n' '$(TOOLCHAIN) $(subst $(CURDIR)/,,$(COMPILE_$(KIND)))' | \
    sha1sum - $(@D)/$(*F).i) && [ -n "$$3" ] && \
  { [ -f build/cas/$$1$$3.o ] || { (cd $(@D) && $(COMPILE_$(KIND))) && mv -f $(@D)/$(*F).o build/cas/$$1$$3.o; }; } && \
  if [ ! -f $(@D)/$(*F).key ] || [ "$$(cat $(@D)/$(*F).key)" != "$$1$$3" ]; then \
    printf '%s\n' $$1$$3 > $(@D)/$(*F).key; fi
LINK_BIN = $(LD) -T versions/$(VER)/$(NAME).ld --section-start=.text=$(firstword $(subst :, ,$($(VER).U.$(*F)))) \
  --oformat binary -o $@ $(@D)/$(*F).placed.o
UNIT_BIN = read key < $< && \
  $(N64LINK) place build/cas/$$key.o -o $(@D)/$(*F).placed.o --rom $($(VER).BASEROM) --text $($(VER).U.$(*F)) \
  $(addprefix --map ,$($(VER).MAP)) --symbols versions/$(VER)/symbols.ld $(TRIM) && \
  $(LINK_BIN)
HASM_BIN = printf '%s\n' '$(VER) $(*F)'; \
  $(AS) $(HASM_ASFLAGS) -o $(@D)/$(*F).o $< && \
  $(N64LINK) place $(@D)/$(*F).o -o $(@D)/$(*F).placed.o --rom $($(VER).BASEROM) --text $($(VER).U.$(*F)) \
  $(addprefix --map ,$($(VER).MAP)) --symbols versions/$(VER)/symbols.ld --trim && \
  $(LINK_BIN)
DATA_BIN = $(if $($(VER).D.$(*F).SECTION),$(MIXED_DATA_BIN),$(PLAIN_DATA_BIN))
PLAIN_DATA_BIN = read key < $< && \
  cp build/cas/$$key.o $(@D)/$(*F).o && \
  $(OBJCOPY) --set-section-flags .rdata=alloc,load,readonly,data,contents \
    --set-section-flags .rodata=alloc,load,readonly,data,contents \
    --set-section-flags .data=alloc,load,data,contents \
    --set-section-flags .sdata=alloc,load,data,contents $(@D)/$(*F).o && \
  $(LD) -EB -T versions/$(VER)/$(NAME).data.ld \
    --section-start=.data=$(firstword $(subst :, ,$($(VER).D.$(*F)))) \
    -o $(@D)/$(*F).elf $(@D)/$(*F).o && \
  $(OBJCOPY) -O binary --only-section=.data $(@D)/$(*F).elf $@ && \
  [ "$$(wc -c < $@)" -eq $$(( $(word 3,$(subst :, ,$($(VER).D.$(*F)))) )) ]
MIXED_TOOL = PYTHONPATH=tools/report-verifier.zip python3 -m unbake.objects.mixed
MIXED_ARGS = --section $($(VER).D.$(*F).SECTION) --offset $($(VER).D.$(*F).OFFSET) \
  --size $(word 3,$(subst :, ,$($(VER).D.$(*F)))) --bias $($(VER).D.$(*F).BIAS) \
  --function $(*F) --text $(firstword $(subst :, ,$($(VER).U.$(*F))))
MIXED_DATA_BIN = read key < build/$(VER)/src/$(*F).key && \
  $(MIXED_TOOL) prepare --original build/cas/$$key.o --placed build/$(VER)/units/$(*F).placed.o \
    --output $(@D)/$(*F).o $(MIXED_ARGS) && \
  $(OBJCOPY) --set-section-flags $($(VER).D.$(*F).SECTION)=alloc,load,readonly,data,contents $(@D)/$(*F).o && \
  $(LD) -EB -T versions/$(VER)/data/$(*F).ld -o $(@D)/$(*F).elf $(@D)/$(*F).o && \
  $(MIXED_TOOL) extract --original build/cas/$$key.o --final $(@D)/$(*F).elf \
    --code build/$(VER)/units/$(*F).bin --output $@ $(MIXED_ARGS)
RESOURCE_NAME = $(basename $(notdir $@))
RESOURCE_BIN = $(AS) $($(VER).R.$(RESOURCE_NAME).ASFLAGS) -o $(@D)/$(RESOURCE_NAME).o $< && \
  $(LD) -EB -T versions/$(VER)/resources/$(RESOURCE_NAME).ld \
    -o $(@D)/$(RESOURCE_NAME).elf $(@D)/$(RESOURCE_NAME).o && \
  $(OBJCOPY) -O binary --only-section=.resource $(@D)/$(RESOURCE_NAME).elf $@ && \
  [ "$$(wc -c < $@)" -eq $$(( $(word 3,$(subst :, ,$($(VER).R.$(RESOURCE_NAME)))) )) ]
SLICE = dd if=$($(VER).BASEROM) of=$@ bs=65536 iflag=skip_bytes,count_bytes status=none \
  skip=$(word 1,$($(VER).S.$(*F))) count=$(word 2,$($(VER).S.$(*F)))
"""

# Every version's units, slices and ROM are targets of one make, so -jN spreads over all of them. A slice is named
# by its start only, so it is cut again whenever slices.mk changes (a new unit can shorten it).
VERSION_RULES = r"""define VERSION_RULES
build/$1/src/%.i: src/%.c Makefile units.mk | verify build/$1/src build/cas
	$$(Q)$$(UNIT_KEY)
build/$1/src/%.key: build/$1/src/%.i
	$$(Q)test -f $$@ || { $$(UNIT_KEY); }
build/$1/units/%.bin: build/$1/src/%.key versions/$1/symbols.ld versions/$1/$$(NAME).ld | build/$1/units
	$$(Q)$$(UNIT_BIN)
build/$1/hasm/%.bin: src/%.s Makefile versions/$1/symbols.ld versions/$1/$$(NAME).ld | build/$1/hasm
	$$(Q)$$(HASM_BIN)
build/$1/data/%.bin: build/$1/src/%.key versions/$1/slices.mk \
  versions/$1/symbols.ld versions/$1/$$(NAME).data.ld | build/$1/data
	$$(Q)$$(DATA_BIN)
build/$1/slices/%.bin: $$($1.BASEROM) versions/$1/slices.mk | build/$1/slices
	$$(Q)$$(SLICE)
build/$1/$$(NAME).z64: $$($1.PIECES)
	$$(Q)printf '%s\n' '$1 rom'; cat $$($1.PIECES) > $$@
build/$1/src build/$1/units build/$1/hasm build/$1/data build/$1/resources build/$1/slices:
	$$(Q)mkdir -p $$@
endef
$(foreach v,$(VERSIONS),$(eval $(call VERSION_RULES,$v)))
build/cas:
	$(Q)mkdir -p $@
"""

# Without -j on the command line, run one job per core (nproc, coreutils); make 4.4 honours -j set here.
JOBS = """ifeq ($(filter -j%,$(MAKEFLAGS)),)
JOBS := $(shell nproc)
$(if $(JOBS),,$(error nproc printed no core count; run make -jN))
MAKEFLAGS += -j$(JOBS)
endif
"""

# make V=1 echoes every command; otherwise a unit prints one line and errors print in full.
QUIET = "Q = $(if $(filter 1,$(V)),,@)\n"

# rom builds one version; VERSION must name a configured one.
ROM = """ifdef VERSION
ifeq ($(filter $(VERSION),$(VERSIONS)),)
$(error VERSION=$(VERSION) is not one of $(VERSIONS))
endif
endif
rom: $(if $(VERSION),build/$(VERSION)/$(NAME).z64)
	@$(if $(VERSION),,$(error make rom needs VERSION=<one of $(VERSIONS)>))sha1sum -c versions/$(VERSION)/$(NAME).sha1
"""


def setup_recipe(project: Project) -> list[str]:
    """Fetch and verify every configured compiler from its registry downloads (curl, tar, sha256sum)."""
    lines = []
    specs = compiler_registry.registry()
    for ident in sorted(project.compilers):
        spec = specs[ident]
        covered = {name for download in spec.downloads for name in download.files}
        missing = sorted(set(spec.pins) - covered)
        if missing:
            lines.append(f"\t@echo 'tools/{ident}: supply {', '.join(missing)} yourself (see README)'")
        for index, download in enumerate(spec.downloads):
            archive = f"tools/.downloads/{download.sha256}.tar.gz"
            unpack = f"tools/.downloads/{ident}-{index}"
            lines.append(f"\t@mkdir -p tools/.downloads tools/{ident} {unpack}")
            lines.append(f"\t@test -f {archive} || curl -fsSL -o {archive} {download.url}")
            lines.append(f"\t@echo '{download.sha256}  {archive}' | sha256sum --quiet -c")
            lines.append(f"\t@tar -xzf {archive} -C {unpack}")
            for name in download.files:
                pin = spec.pins[name]
                lines.append(
                    f"\t@for f in $$(find {unpack} -type f -name '{Path(name).name}'); do "
                    f'[ "$$(sha256sum < $$f | cut -c1-64)" = {pin} ] && cp $$f tools/{ident}/{name} '
                    f"&& chmod 755 tools/{ident}/{name} && break; done"
                )
            lines.append(f"\t@rm -rf {unpack}")
    return lines


def makefile(project: Project, host: Host) -> str:
    default = project.compilers[project.default_compiler]
    c_includes, c_codegen, c_defines = drivers.compiler_parts(project, default.id)
    default_preprocess, _ = drivers.stage_flags(default.id, list(default.cflags))
    includes = [f"-I{relative(project, path)}" for path in project.include]
    kinds = sorted({compiler.kind for compiler in project.compilers.values()})
    text = [
        HEADER,
        "# make check            build every version in one parallel graph and compare each ROM with the original\n",
        "# make VERSION=<v> rom  build one version\n",
        "# make setup            fetch and verify the compilers into tools/\n",
        "# make verify           check the compilers, n64link and the original ROMs\n",
        "# make V=1 ...          echo every command\n",
        "# Without -jN make runs one job per core. Identical compiler inputs compile once (build/cas).\n",
        "# Tools come from PATH (make, cpp, mips binutils, n64link, coreutils, curl, tar) or as\n",
        "# make CPP=... AS=... LD=... N64LINK=... on the command line.\n",
        # .SECONDARY: keys, placed objects and slices are intermediates of chained rules; keep them.
        "SHELL := /bin/sh\n.SUFFIXES:\n.DELETE_ON_ERROR:\n.SECONDARY:\n",
        JOBS,
        QUIET,
        f"NAME := {project.name}\n",
        f"VERSIONS := {' '.join(project.versions)}\n",
        "ROMS := $(foreach v,$(VERSIONS),build/$v/$(NAME).z64)\n",
        "CPP := cpp\nAS := mips-linux-gnu-as\nLD := mips-linux-gnu-ld\n",
        "N64LINK := n64link\nOBJCOPY := mips-linux-gnu-objcopy\nARMIPS := armips\n",
        f"INCLUDES := {words(includes)}\n",
        f"CPPFLAGS := {words(list(project.cppflags))}\n",
        f"PREPROCESS_FLAGS = $(INCLUDES) {words(list(default_preprocess))} $(VERSION_DEFINES) $(CONSUMER)\n",
        f"ASSEMBLER_FLAGS := {words(list(drivers.assembly_flags(project, default.id)))}\n",
        f"HASM_ASFLAGS := {words(list(project.asflags))}\n",
        f"KIND := {default.kind}\n",
        f"CC := {relative(project, default.cc)}\n",
        f"CODEGEN := {words(c_codegen)}\n",
        f"COMPILER_INCLUDES := {words(c_includes)}\n",
        f"COMPILER_DEFINES := {words(c_defines)}\n",
        f"TRIM := {'' if drivers.preserves_padding(default.kind) else '--trim'}\n",
        "UNIT_INCLUDES :=\nUNIT_CODEGEN :=\nUNIT_DEFINES :=\nCONSUMER :=\n",
        "\n.PHONY: all check verify setup clean rom\nall: check\n\n",
        "check: verify $(ROMS)\n",
        "\t@sha1sum -c $(foreach v,$(VERSIONS),versions/$v/$(NAME).sha1)\n\n",
        ROM,
        "\nverify:\n",
        "\t@sha256sum --quiet -c tools/compilers.sha256\n",
        '\t@test "$$($(N64LINK) --version)" = "$$(cat tools/n64link.version)" '
        "|| { echo 'n64link: expected' \"$$(cat tools/n64link.version)\"; exit 1; }\n",
        "\t@sha1sum --quiet -c $(foreach v,$(VERSIONS),versions/$v/baserom.sha1)\n\n",
        "setup:\n",
        *(line + "\n" for line in setup_recipe(project)),
        "\t@sha256sum --quiet -c tools/compilers.sha256\n\n",
        "clean:\n\trm -rf build/cas "
        "$(foreach v,$(VERSIONS),build/$v/src build/$v/units build/$v/hasm "
        "build/$v/data build/$v/resources build/$v/slices)\n\n",
        "include $(foreach v,$(VERSIONS),versions/$v/slices.mk)\n",
        "include units.mk\n\n",
        *(_kind_recipes(kind) for kind in kinds),
        UNIT_RECIPES,
        "\n",
        VERSION_RULES,
        "\n-include $(wildcard build/*/src/*.d)\n",
    ]
    return "".join(text)


def _pinned(action: tuple[str, str, str]) -> str:
    name, sha, tag = action
    if len(sha) != 40 or any(c not in "0123456789abcdef" for c in sha):
        raise Held(
            cause_named(
                "buildfiles.ci_pin",
                f"buildfiles.ci_pin: {name}: a full 40-hex commit SHA is required",
                owner="buildfiles",
                stage="buildfiles",
            )
        )
    return f"{name}@{sha} # {tag}"


def _quoted(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _progress_verifier(payload: bytes | None = None) -> list[str]:
    from unbake.report import verify

    digest = hashlib.sha256(verify.bundle() if payload is None else payload).hexdigest()
    return [
        f"echo '{digest}  {verify.BUNDLE}' | sha256sum -c -",
        "verifier_dir=$(mktemp -d)",
        f'python3 -m zipfile -e {verify.BUNDLE} "$verifier_dir"',
        'PYTHONPATH="$verifier_dir" python3 -m unbake.report.verify --project . --artifacts out',
    ]


def github_progress(
    project: Project, host: Host | None, *, publish_branch: str | None = None, verifier_payload: bytes | None = None
) -> str:
    """Verify source semantics with a content-pinned tool before publishing version reports."""
    branch = host.publish_branch if host is not None else publish_branch
    if branch is None:
        raise Held(
            cause_named("buildfiles.publish_branch", "owning branch required", owner="buildfiles", stage="buildfiles")
        )
    commands = _progress_verifier(verifier_payload)
    lines = [
        HEADER,
        "name: progress\n",
        "on:\n  push:\n    branches: [" + _quoted(branch) + "]\n  workflow_dispatch:\n",
        "permissions:\n  contents: read\n",
        "jobs:\n  progress:\n    runs-on: ubuntu-latest\n    steps:\n",
        f"      - uses: {_pinned(CHECKOUT)}\n",
        "      - name: Verify current source and report semantics\n        run: |\n",
        "          set -eu\n",
        *(f"          {command}\n" for command in commands),
    ]
    copies = " && ".join(f"cp versions/{v}/report.json out/{v}_report.json" for v in project.versions)
    lines.append(f"      - run: {copies}\n")
    for version in project.versions:
        lines.append(
            f"      - uses: {_pinned(UPLOAD_ARTIFACT)}\n"
            f"        with:\n          name: {_quoted(version + '_report')}\n"
            f"          path: |\n            out/{version}_report.json\n"
            f"            out/{version}_report.manifest.json\n"
            "          if-no-files-found: error\n"
        )
    return "".join(lines)


def gitlab_progress(project: Project, *, verifier_payload: bytes | None = None) -> str:
    """Identical semantic verifier and artifact mapping, without private ROM inputs."""
    commands = "\n".join(_progress_verifier(verifier_payload))
    lines = [
        HEADER,
        "progress:\n",
        f"  image: {_quoted(PYTHON_IMAGE)}\n",
        "  rules:\n    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n",
        "  script:\n    - |\n        set -eu\n",
        *(f"        {command}\n" for command in commands.splitlines()),
        *(f"    - cp versions/{v}/report.json out/{v}_report.json\n" for v in project.versions),
        "  artifacts:\n    paths:\n      - out/*_report.json\n      - out/*_report.manifest.json\n",
    ]
    return "".join(lines)


def write_progress(project: Project, *, publish_branch: str) -> list[Path]:
    """Regenerate the owning progress CI and pinned payload without private ROM inputs."""
    from unbake.report import verify

    payload = verify.bundle()
    outputs = {
        project.root / verify.BUNDLE: payload,
        project.root / ".github/workflows/progress.yml": github_progress(
            project, None, publish_branch=publish_branch, verifier_payload=payload
        ).encode(),
        project.root / ".gitlab-ci.yml": gitlab_progress(project, verifier_payload=payload).encode(),
    }
    for path, content in outputs.items():
        if not path.is_file() or path.read_bytes() != content:
            atomic_files.write(path, content)
    return list(outputs)


# The n64link release these build files need: 0.3.1 relocates jump-table words before its ROM proof.
N64LINK_RELEASE = drivers.assembler_release()


def n64link_pin(host: Host) -> str:
    """The n64link release the build files expect; the host's n64link must print exactly that release."""
    from unbake import process

    printed = process.run_tool(
        [str(host.n64link), "--version"],
        Path(host.n64link).parent,
        "buildfiles",
        temporary_root=host.cache_machine_root,
    )
    if printed != N64LINK_RELEASE:
        required = N64LINK_RELEASE.strip()
        actual = printed.strip()
        raise Held(
            cause_named(
                "buildfiles.n64link",
                f"buildfiles.n64link: {host.n64link} prints {actual!r}; {required!r} is required",
                owner="buildfiles",
                stage="buildfiles",
            )
        )
    return N64LINK_RELEASE


def generate(project: Project, host: Host) -> dict[Path, bytes]:
    """Every build file, by path; refused when an original-asm source or row lacks its proved record."""
    from unbake.decomp import original_asm

    original_asm.guard(project)
    from unbake.report import verify

    payload = verify.bundle()
    from unbake.project import hygiene

    files: dict[Path, str] = {
        project.root / ".gitignore": hygiene.runtime_ignore_text(project),
        project.root / "Makefile": makefile(project, host),
        project.root / "units.mk": units_mk(project),
        project.tools / "n64link.version": n64link_pin(host),
        project.root / ".github/workflows/progress.yml": github_progress(project, host, verifier_payload=payload),
        project.root / ".gitlab-ci.yml": gitlab_progress(project, verifier_payload=payload),
    }
    for version in project.versions:
        directory = project.root / "versions" / version
        meta = project.version(version)
        rom = relative(project, meta.baserom)
        files[directory / "slices.mk"] = slices_mk(project, version)
        files[directory / "symbols.ld"] = symbols_ld(project, version)
        files[directory / f"{project.name}.ld"] = link_script(project, version)
        files[directory / f"{project.name}.data.ld"] = data_link_script(project, version)
        for unit in data_units(project, version):
            if isinstance(unit, MixedData):
                files[directory / "data" / f"{unit.name}.ld"] = mixed_data_link_script(project, version, unit)
        for resource in resource_bindings(project, version):
            if resource.assembler == "gnu":
                files[directory / "resources" / f"{resource.name}.ld"] = resource_link_script(
                    project, version, resource
                )
        files[directory / "baserom.sha1"] = f"{meta.baserom_sha1}  {rom}\n"
        files[directory / f"{project.name}.sha1"] = f"{meta.baserom_sha1}  build/{version}/{project.name}.z64\n"
    return {**{path: text.encode() for path, text in files.items()}, project.root / verify.BUNDLE: payload}


def input_key(project: Project, host: Host) -> str:
    """Everything the build files are made from."""
    from unbake.report import verify

    parts: list[str | bytes | Path] = [
        "buildfiles",
        str(SCHEMA),
        hashlib.sha256(verify.bundle()).hexdigest(),
        project.root / "config.toml",
        Path(host.n64link),
        host.publish_branch,
    ]
    for version in project.versions:
        meta = project.version(version)
        parts.extend([meta.split, meta.symbols, meta.baserom_sha1])
    # Contents, not just names: symbols.ld provides the address-named symbols these files spell.
    parts.extend(sorted(project.src.glob("*.c")))
    parts.extend(sorted(project.src.glob("*.s")))
    parts.extend(sorted((project.root / "resources").rglob("*.s")))
    parts.extend(resource_inputs(project))
    from unbake.project import hygiene

    parts.append(hygiene.runtime_ignore_text(project))
    from unbake.decomp import original_asm

    manifest = project.root / original_asm.MANIFEST
    parts.append(manifest if manifest.is_file() else "no original asm")
    for include in project.include:
        parts.extend(sorted(include.rglob("*.h")))
    return cache.key(
        *(
            inputs.digest(part, algorithm="sha256", reuse=retention.configured()) if isinstance(part, Path) else part
            for part in parts
        )
    )


def drift(project: Project, host: Host) -> list[Path]:
    """Build and CI files whose bytes differ from the generator's output (check --files-only reports these)."""
    return [
        path for path, content in generate(project, host).items() if not path.is_file() or path.read_bytes() != content
    ]


def write(project: Project, host: Host) -> list[Path]:
    """Write the build files whose bytes changed; return them."""
    generated = generate(project, host)
    changed = [path for path, content in generated.items() if not path.is_file() or path.read_bytes() != content]
    for path in changed:
        atomic_files.write(path, generated[path])
    return changed
