"""The committed, Python-free build: Makefile, units.mk and per-version slices, symbols and link scripts.

A version's ROM is the concatenation, in ROM order, of
- one binary per published C unit (compile, `n64link place`, link alone at its address with symbols.ld), and
- raw ROM slices for every byte range between them (copied from the original ROM with dd).
`make check` rebuilds every version and compares each ROM's sha1 with the original. The commands per unit come
from compilers.drivers, the same templates the runner fills, so make and unbake never disagree.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from unbake import atomic as atomic_files
from unbake import cache, steps
from unbake.compilers import drivers
from unbake.compilers import registry as compiler_registry
from unbake.config import Held, Host, Project
from unbake.layout import split

# CI pins: full commit SHAs and an image digest (tool data, never config).
CHECKOUT = ("actions/checkout", "11d5960a326750d5838078e36cf38b85af677262", "v4.4.0")
UPLOAD_ARTIFACT = ("actions/upload-artifact", "ea165f8d65b6e75b540449e92b4886f43607fa02", "v4.6.2")
BUSYBOX = "busybox@sha256:bdf57e528e45e4433820e045b29b4597825a1c9e38353532d90a01445013f82e"
HEADER = "# Generated by unbake. Do not edit; unbake regenerates it from config.toml and versions/.\n"
MAKE_VALUES: dict[str, tuple[str, ...]] = {
    "cc": ("$(abspath $(CC))",),
    "cpp": ("$(CPP)",),
    "as": ("$(AS)",),
    "n64link": ("$(N64LINK)",),
    "includes": ("$(INCLUDES) $(COMPILER_INCLUDES) $(UNIT_INCLUDES)",),
    "codegen": ("$(CODEGEN) $(UNIT_CODEGEN)",),
    "defines": ("$(COMPILER_DEFINES) $(VERSION_DEFINES) $(CONSUMER) $(UNIT_DEFINES)",),
    "cppflags": ("$(CPPFLAGS)",),
    "asflags": ("$(SN64_ASFLAGS)",),
    "source": ("$<",),
    "name": ("$(*F)",),
}


@dataclass(frozen=True)
class Unit:
    """One published C unit in one version: its row in the ROM."""

    name: str
    address: int
    start: int
    size: int


def relative(project: Project, path: Path) -> str:
    return str(path.relative_to(project.root)) if path.is_relative_to(project.root) else str(path)


def words(values: tuple[str, ...] | list[str]) -> str:
    for value in values:
        if any(c in value for c in " \t\n'\"$#\\"):
            raise Held("buildfiles", f"buildfiles.flag: {value!r}: flags may not contain spaces, quotes, $, # or \\")
    return " ".join(values)


def units(project: Project, version: str) -> list[Unit]:
    """Published C rows of VERSION in ROM order; each must have src/<unit>.c."""
    result = []
    for row in split.functions(project, version):
        if row.kind != "c":
            continue
        name = Path(row.path).name
        if not (project.src / f"{name}.c").is_file():
            raise Held("buildfiles", f"buildfiles.source: {version} row {name} has no src/{name}.c")
        result.append(Unit(name, row.address, row.start, row.end - row.start))
    return sorted(result, key=lambda unit: unit.start)


def windows(project: Project, version: str) -> list[tuple[int, int, int]]:
    """(vram, rom, size) for every mapped segment and resident copy; place proves constants inside them."""
    _, _, segments = split.layout(project.version(version).split)
    result = []
    for segment in segments:
        fields = segment.fields
        if "vram" not in fields or "start" not in fields or segment.end is None:
            continue
        start = split.number(fields["start"], "segment start")
        result.append((split.number(fields["vram"], "segment vram"), start, segment.end - start))
    for mapping in project.resident_mappings.get(version, ()):
        result.append((mapping.address, mapping.start, mapping.end - mapping.start))
    return result


_ADDRESS_NAMED = re.compile(r"\b(?:D|func)_([0-9A-F]{8})\b")


def address_named(project: Project) -> dict[str, int]:
    """Names splat derives from a vram (D_XXXXXXXX, func_XXXXXXXX) that published C or headers spell."""
    names: dict[str, int] = {}
    for path in (*project.src.glob("*.c"), *(p for root in project.include for p in root.rglob("*.h"))):
        for match in _ADDRESS_NAMED.finditer(path.read_text(errors="replace")):
            names[match[0]] = int(match[1], 16)
    return names


def symbols_ld(project: Project, version: str) -> str:
    """Every known symbol as PROVIDE, so a unit linked alone resolves its external references.

    Data that stays a raw ROM slice has no label in any object. In the naming version a referenced
    address-named symbol missing from the symbol file is provided at the address its name encodes;
    a wrong address cannot pass, because make check compares the whole ROM.
    """
    _, rows = split.symbols(project.version(version).symbols)
    provided = {name: address for name, (address, _, _) in rows.items()}
    if version == project.names_from:
        for name, address in address_named(project).items():
            provided.setdefault(name, address)
    return "".join(f"PROVIDE({name} = 0x{address:08X});\n" for name, address in sorted(provided.items()))


def link_script(project: Project, version: str) -> str:
    return (
        "OUTPUT_ARCH(mips)\n"
        "SECTIONS\n{\n  .text : { *(.text) }\n  /DISCARD/ : { *(*) }\n}\n"
        f"INCLUDE versions/{version}/symbols.ld\n"
    )


def slices_mk(project: Project, version: str) -> str:
    """Units, raw slices between them, constant windows and the piece order of the ROM.

    Slice offsets and sizes are decimal: GNU dd reads skip= and count= as decimal (0x is a multiplier)."""
    rom_size = project.version(version).baserom.stat().st_size
    lines = [HEADER]
    lines.append(f"BASEROM := {relative(project, project.version(version).baserom)}\n")
    lines.append(f"VERSION_DEFINES := {words(['-D' + macro for macro in project.version(version).macros])}\n")
    lines.append("MAP := " + " ".join(f"0x{v:X}:0x{r:X}:0x{s:X}" for v, r, s in windows(project, version)) + "\n")
    pieces = []
    cursor = 0
    for unit in units(project, version):
        if unit.start < cursor:
            raise Held("buildfiles", f"buildfiles.overlap: {version} {unit.name} starts inside the previous row")
        if unit.start > cursor:
            lines.append(f"S_{cursor:08X} := {cursor} {unit.start - cursor}\n")
            pieces.append(f"$(B)/slices/{cursor:08X}.bin")
        lines.append(f"U_{unit.name} := 0x{unit.address:X}:0x{unit.start:X}:0x{unit.size:X}\n")
        lines.append(f"A_{unit.name} := 0x{unit.address:X}\n")
        pieces.append(f"$(B)/units/{unit.name}.bin")
        cursor = unit.start + unit.size
    if cursor > rom_size:
        raise Held("buildfiles", f"buildfiles.rom_size: {version} rows end past the ROM")
    if cursor < rom_size:
        lines.append(f"S_{cursor:08X} := {cursor} {rom_size - cursor}\n")
        pieces.append(f"$(B)/slices/{cursor:08X}.bin")
    lines.append("PIECES := \\\n" + " \\\n".join(f"  {piece}" for piece in pieces) + "\n")
    return "".join(lines)


def units_mk(project: Project) -> str:
    """Target-specific values for units that differ from the default compiler or carry their own flags."""
    lines = [HEADER]
    default = project.compilers[project.default_compiler]
    names = sorted({path.stem for path in project.src.glob("*.c")})
    for name in names:
        targets = f"$(B)/src/{name}.o $(B)/units/{name}.bin"
        compiler = project.compiler_for(name)
        if compiler.id != default.id:
            c_includes, c_codegen, c_defines = drivers.compiler_parts(project, compiler.id)
            lines.append(f"{targets}: KIND := {compiler.kind}\n")
            lines.append(f"{targets}: CC := {relative(project, compiler.cc)}\n")
            lines.append(f"{targets}: CODEGEN := {words(c_codegen)}\n")
            lines.append(f"{targets}: COMPILER_INCLUDES := {words(c_includes)}\n")
            lines.append(f"{targets}: COMPILER_DEFINES := {words(c_defines)}\n")
            lines.append(f"{targets}: TRIM := {'' if compiler.kind in drivers.UNTRIMMED else '--trim'}\n")
        u_includes, u_codegen, u_defines = drivers.unit_parts(project, name)
        if u_includes:
            lines.append(f"{targets}: UNIT_INCLUDES := {words(u_includes)}\n")
        if u_codegen:
            lines.append(f"{targets}: UNIT_CODEGEN := {words(u_codegen)}\n")
        if u_defines:
            lines.append(f"{targets}: UNIT_DEFINES := {words(u_defines)}\n")
        guard = drivers.consumer_define(project, name)
        if guard is not None:
            lines.append(f"{targets}: CONSUMER := {guard}\n")
    return "".join(lines)


def _recipe(template: tuple[str, ...]) -> str:
    return " ".join(drivers.render(template, MAKE_VALUES))


def _canned(kind: str) -> str:
    template = drivers.TEMPLATES[kind]
    preprocess = template["preprocess"]
    compile_ = template["compile"]
    assert preprocess is not None and compile_ is not None
    lines = [
        f"define COMPILE_{kind}",
        f"\t{_recipe(preprocess)} > $(@D)/$(*F).i",
        f"\tcd $(@D) && {_recipe(compile_)}",
    ]
    if template["assemble"] is not None:
        lines.append(f"\tcd $(@D) && {_recipe(template['assemble'])}")
    lines.append("endef")
    return "\n".join(lines) + "\n"


def setup_recipe(project: Project) -> list[str]:
    """Fetch and verify every configured compiler from its registry downloads (curl, tar, sha256sum)."""
    lines = []
    specs = compiler_registry.registry()
    for ident in sorted(project.compilers):
        spec = specs[ident]
        covered = {name for download in spec.downloads for name in download.files}
        missing = sorted(set(spec.pins) - covered)
        if missing:
            lines.append(f"\t@echo 'tools/{ident}: supply {', '.join(missing)} yourself (see README)'")
        for index, download in enumerate(spec.downloads):
            archive = f"tools/.downloads/{download.sha256}.tar.gz"
            unpack = f"tools/.downloads/{ident}-{index}"
            lines.append(f"\t@mkdir -p tools/.downloads tools/{ident} {unpack}")
            lines.append(f"\t@test -f {archive} || curl -fsSL -o {archive} {download.url}")
            lines.append(f"\t@echo '{download.sha256}  {archive}' | sha256sum --quiet -c")
            lines.append(f"\t@tar -xzf {archive} -C {unpack}")
            for name in download.files:
                pin = spec.pins[name]
                lines.append(
                    f"\t@for f in $$(find {unpack} -type f -name '{Path(name).name}'); do "
                    f'[ "$$(sha256sum < $$f | cut -c1-64)" = {pin} ] && cp $$f tools/{ident}/{name} '
                    f"&& chmod 755 tools/{ident}/{name} && break; done"
                )
            lines.append(f"\t@rm -rf {unpack}")
    return lines


def makefile(project: Project, host: Host) -> str:
    default = project.compilers[project.default_compiler]
    c_includes, c_codegen, c_defines = drivers.compiler_parts(project, default.id)
    includes = [f"-I{relative(project, path)}" for path in project.include]
    depend = " ".join(drivers.render(drivers.DEPEND, MAKE_VALUES))
    kinds = sorted({compiler.kind for compiler in project.compilers.values()})
    text = [
        HEADER,
        "# make check            build every version and compare it with the original ROM (sha1)\n",
        "# make VERSION=<v> rom  build one version\n",
        "# make setup            fetch and verify the compilers into tools/\n",
        "# make verify           check the compilers, n64link and the original ROMs\n",
        "# Tools come from PATH (make, cpp, mips binutils, n64link, coreutils, curl, tar) or as\n",
        "# make CPP=... AS=... LD=... OBJCOPY=... N64LINK=... on the command line.\n",
        # .SECONDARY: objects, placed objects and slices are intermediates of chained rules; keep them.
        "SHELL := /bin/sh\n.SUFFIXES:\n.DELETE_ON_ERROR:\n.SECONDARY:\n",
        f"NAME := {project.name}\n",
        f"VERSIONS := {' '.join(project.versions)}\n",
        "CPP := cpp\nAS := mips-linux-gnu-as\nLD := mips-linux-gnu-ld\nOBJCOPY := mips-linux-gnu-objcopy\n",
        "N64LINK := n64link\n",
        f"INCLUDES := {words(includes)}\n",
        f"CPPFLAGS := {words(list(project.cppflags))}\n",
        f"SN64_ASFLAGS := {words(list(drivers.gnu_as_flags(project)))}\n",
        f"KIND := {default.kind}\n",
        f"CC := {relative(project, default.cc)}\n",
        f"CODEGEN := {words(c_codegen)}\n",
        f"COMPILER_INCLUDES := {words(c_includes)}\n",
        f"COMPILER_DEFINES := {words(c_defines)}\n",
        f"TRIM := {'' if default.kind in drivers.UNTRIMMED else '--trim'}\n",
        "UNIT_INCLUDES :=\nUNIT_CODEGEN :=\nUNIT_DEFINES :=\nCONSUMER :=\n",
        "\n.PHONY: all check verify setup clean rom\nall: check\n\n",
        "check: verify\n",
        "\t@for v in $(VERSIONS); do $(MAKE) --no-print-directory VERSION=$$v rom || exit 1; done\n\n",
        "verify:\n",
        "\t@sha256sum --quiet -c tools/compilers.sha256\n",
        '\t@test "$$($(N64LINK) --version)" = "$$(cat tools/n64link.version)" '
        "|| { echo 'n64link: expected' \"$$(cat tools/n64link.version)\"; exit 1; }\n",
        "\t@for v in $(VERSIONS); do sha1sum --quiet -c versions/$$v/baserom.sha1 || exit 1; done\n\n",
        "setup:\n",
        *(line + "\n" for line in setup_recipe(project)),
        "\t@sha256sum --quiet -c tools/compilers.sha256\n\n",
        "clean:\n\trm -rf build/*/src build/*/units build/*/slices\n\n",
        "ifdef VERSION\n",
        "B := build/$(VERSION)\n",
        "include versions/$(VERSION)/slices.mk\n",
        "include units.mk\n\n",
        *(_canned(kind) + "\n" for kind in kinds),
        "rom: $(B)/$(NAME).z64\n\tsha1sum --quiet -c versions/$(VERSION)/$(NAME).sha1\n\n",
        "$(B)/$(NAME).z64: $(PIECES)\n\tcat $(PIECES) > $@\n\n",
        "$(B)/slices/%.bin: $(BASEROM)\n\t@mkdir -p $(@D)\n",
        "\tdd if=$(BASEROM) of=$@ bs=65536 iflag=skip_bytes,count_bytes status=none "
        "skip=$(word 1,$(S_$*)) count=$(word 2,$(S_$*))\n\n",
        "$(B)/src/%.o: src/%.c Makefile units.mk\n\t@mkdir -p $(@D)\n",
        f"\t{depend} -MT $@ -MF $(@D)/$(*F).d\n",
        "\t$(COMPILE_$(KIND))\n\n",
        "$(B)/units/%.bin: $(B)/src/%.o versions/$(VERSION)/symbols.ld versions/$(VERSION)/$(NAME).ld\n",
        "\t@mkdir -p $(@D)\n",
        "\t$(N64LINK) place $< -o $(@D)/$*.placed.o --rom $(BASEROM) --text $(U_$*) "
        "$(addprefix --map ,$(MAP)) --symbols versions/$(VERSION)/symbols.ld $(TRIM)\n",
        "\t$(LD) -EB -T versions/$(VERSION)/$(NAME).ld --section-start=.text=$(A_$*)"
        " -o $(@D)/$*.elf $(@D)/$*.placed.o\n",
        "\t$(OBJCOPY) -O binary -j .text $(@D)/$*.elf $@\n\n",
        "-include $(wildcard $(B)/src/*.d)\n",
        "endif\n",
    ]
    return "".join(text)


def _pinned(action: tuple[str, str, str]) -> str:
    name, sha, tag = action
    if len(sha) != 40 or any(c not in "0123456789abcdef" for c in sha):
        raise Held("buildfiles", f"buildfiles.ci_pin: {name}: a full 40-hex commit SHA is required")
    return f"{name}@{sha} # {tag}"


def _quoted(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def github_progress(project: Project, host: Host) -> str:
    """Upload versions/<v>/report.json as artifact <v>_report holding <v>_report.json (what decomp.dev reads)."""
    branch = host.publish_branch
    lines = [
        HEADER,
        "name: progress\n",
        "on:\n  push:\n    branches: [" + _quoted(branch) + "]\n  workflow_dispatch:\n",
        "permissions:\n  contents: read\n",
        "jobs:\n  progress:\n    runs-on: ubuntu-latest\n    steps:\n",
        f"      - uses: {_pinned(CHECKOUT)}\n",
    ]
    copies = " && ".join(f"cp versions/{v}/report.json out/{v}_report.json" for v in project.versions)
    lines.append(f"      - run: mkdir -p out && {copies}\n")
    for version in project.versions:
        lines.append(
            f"      - uses: {_pinned(UPLOAD_ARTIFACT)}\n"
            f"        with:\n"
            f"          name: {_quoted(version + '_report')}\n"
            f"          path: {_quoted('out/' + version + '_report.json')}\n"
            f"          if-no-files-found: error\n"
        )
    return "".join(lines)


def gitlab_progress(project: Project) -> str:
    """The same reports as GitLab job artifacts on the default branch."""
    lines = [
        HEADER,
        "progress:\n",
        f"  image: {_quoted(BUSYBOX)}\n",
        "  rules:\n    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n",
        "  script:\n    - mkdir -p out\n",
        *(f"    - cp versions/{v}/report.json out/{v}_report.json\n" for v in project.versions),
        "  artifacts:\n    paths:\n      - out/*_report.json\n",
    ]
    return "".join(lines)


def n64link_pin(host: Host) -> str:
    """The n64link release the build files expect; any build of that release passes make verify."""
    from unbake import process

    return process.run_tool([str(host.n64link), "--version"], Path(host.n64link).parent, "buildfiles")


def generate(project: Project, host: Host) -> dict[Path, bytes]:
    """Every build file, by path."""
    files: dict[Path, str] = {
        project.root / "Makefile": makefile(project, host),
        project.root / "units.mk": units_mk(project),
        project.tools / "n64link.version": n64link_pin(host),
        project.root / ".github/workflows/progress.yml": github_progress(project, host),
        project.root / ".gitlab-ci.yml": gitlab_progress(project),
    }
    for version in project.versions:
        directory = project.root / "versions" / version
        meta = project.version(version)
        rom = relative(project, meta.baserom)
        files[directory / "slices.mk"] = slices_mk(project, version)
        files[directory / "symbols.ld"] = symbols_ld(project, version)
        files[directory / f"{project.name}.ld"] = link_script(project, version)
        files[directory / "baserom.sha1"] = f"{meta.baserom_sha1}  {rom}\n"
        files[directory / f"{project.name}.sha1"] = f"{meta.baserom_sha1}  build/{version}/{project.name}.z64\n"
    return {path: text.encode() for path, text in files.items()}


def input_key(project: Project, host: Host) -> str:
    """Everything the build files are made from."""
    parts: list[str | bytes | Path] = [
        steps.tool_fingerprint(),
        project.root / "config.toml",
        Path(host.n64link),
        host.publish_branch,
    ]
    for version in project.versions:
        meta = project.version(version)
        parts.extend([meta.split, meta.symbols, meta.baserom_sha1])
    # Contents, not just names: symbols.ld provides the address-named symbols these files spell.
    parts.extend(sorted(project.src.glob("*.c")))
    for include in project.include:
        parts.extend(sorted(include.rglob("*.h")))
    return cache.key(*parts)


def drift(project: Project, host: Host) -> list[Path]:
    """Build and CI files whose bytes differ from the generator's output (check --files-only reports these)."""
    return [
        path for path, content in generate(project, host).items() if not path.is_file() or path.read_bytes() != content
    ]


def write(project: Project, host: Host) -> list[Path]:
    """Write the build files whose bytes changed; return them."""
    changed = []
    for path, content in generate(project, host).items():
        if path.is_file() and path.read_bytes() == content:
            continue
        atomic_files.write(path, content)
        changed.append(path)
    return changed
